In [1]:
import pandas as pd
import numpy as np

### 감탄 떡볶이의 입점전략은 파리바게트옆인가?
- 감탄떡볶이의 입점전략이 파리바게트 옆인지 알아보기위해
- 감탄떡볶이외 국대떡볶이, 죠스떡볶이, 엽기떡볶이, 신전떡볶이와 파리바게트의 거리를 구해서 비교

In [2]:
pd.options.display.float_format = '{:.4f}'.format # 소수점 네자리 까지만 출력
url = 'https://raw.githubusercontent.com/panda-kim/csv_files/main/food_business_seoul_20221231.csv'
tt = ['감탄떡볶이', '국대떡볶이', '죠스떡볶이', '엽기떡볶이', '신전떡볶이']

In [3]:
df = pd.read_csv(url)
df

,상가업소번호,상호명,지점명,상권업종중분류명,상권업종소분류명,시군구명,행정동명,도로명주소,경도,위도
0,17174175,비지트,NaN,한식,한식/백반/한정식,서초구,방배4동,서울특별시 서초구 동광로18길 82,126.9914,37.4884
1,17174119,쓰리에프,NaN,한식,한식/백반/한정식,동작구,사당2동,서울특별시 동작구 동작대로27가길 12,126.9810,37.4871
2,17174040,다향,NaN,한식,한식/백반/한정식,서초구,서초3동,서울특별시 서초구 효령로 230,127.0094,37.4834
3,25530299,고향생막걸리,NaN,유흥주점,민속주점,강남구,압구정동,서울특별시 강남구 압구정로 216,127.0310,37.5281
4,17163092,도전최강달인왕만두,NaN,한식,한식/백반/한정식,강동구,고덕2동,서울특별시 강동구 고덕로 353,127.1595,37.5562
...,...,...,...,...,...,...,...,...,...,...
90827,17267551,소머리국밥,NaN,한식,한식/백반/한정식,관악구,삼성동,서울특별시 관악구 원신5길 1,126.9318,37.4691
90828,17257002,담,NaN,한식,한식/백반/한정식,서초구,서초3동,서울특별시 서초구 남부순환로 2364,127.0098,37.4777
90829,17264432,북창동순두부,서초반포점,한식,한식/백반/한정식,서초구,반포1동,서울특별시 서초구 주흥길 10,127.0208,37.5043
90830,17258497,혼밥순대국,NaN,한식,한식/백반/한정식,서초구,반포1동,서울특별시 서초구 강남대로 523,127.0220,37.5087
90831,17266145,부산아지매국밥,신논현역점,한식,한식/백반/한정식,강남구,논현1동,서울특별시 강남구 강남대로112길 30,127.0268,37.5057

In [4]:
# 파리바게뜨 데이터 필터링하고 정제하기
cond1 = df['상호명'].str.contains(r'파리바게뜨|파리바게트')
df_paris = df.loc[cond1, ['상가업소번호', '경도', '위도']].copy()
df_paris = df_paris.set_axis(['p_업소번호', 'p_경도', 'p_위도'], axis=1).reset_index(drop=True)
df_paris

       p_업소번호     p_경도    p_위도
0    26669769 126.8839 37.4903
1     9171904 127.0330 37.6078
2    23396020 126.9886 37.5742
3    20022143 126.9315 37.5193
4    15484881 127.1477 37.5397
..        ...      ...     ...
354  20072828 126.9138 37.4870
355  20623717 126.8342 37.5402
356  20589842 126.9019 37.4522
357  20595157 127.1310 37.5101
358  17182192 127.1644 37.5569

[359 rows x 3 columns]

In [5]:
# 떡볶이 프랜차이즈 데이터 필터링하고 정제하기
df_tt = df.copy()
# df_tt['상호명'].str.extract('(감탄떡볶이|국대떡볶이)').dropna()
df_tt['상호명'] = df_tt['상호명'].str.extract(r'({})'.format('|'.join(tt)))[0]
df_tt = df_tt.dropna(subset=['상호명']).iloc[:, [0, 1, 5, 8, 9]].reset_index(drop=True)
df_tt

       상가업소번호    상호명  시군구명       경도      위도
0    20844443  신전떡볶이   중랑구 127.1014 37.6003
1    25541815  신전떡볶이   중랑구 127.0794 37.6119
2    20738752  엽기떡볶이   양천구 126.8535 37.5210
3    28513476  엽기떡볶이  동대문구 127.0343 37.5863
4    28514842  엽기떡볶이   용산구 126.9995 37.5284
..        ...    ...   ...      ...     ...
255  14063129  신전떡볶이   용산구 126.9521 37.5345
256  27925379  엽기떡볶이    중구 127.0155 37.5666
257  23444901  죠스떡볶이  영등포구 126.9058 37.5140
258  16990013  신전떡볶이   용산구 126.9992 37.5278
259  20081411  국대떡볶이   서초구 126.9966 37.4814

[260 rows x 5 columns]

In [6]:
# 곱집합(cartesian product) & 위도와 경도로 거리구하기(haversine)
df1 = pd.DataFrame(['A', 'B'])
df2 = pd.DataFrame(['가', '나', '다'])
df1.merge(df2, how='cross') # cross join 모든 순서쌍 구함.

  0_x 0_y
0   A   가
1   A   나
2   A   다
3   B   가
4   B   나
5   B   다

In [7]:
# df_tt와 df_paris의 곱집합 만들기
df_cross = df_tt.merge(df_paris, how='cross')
df_cross

         상가업소번호    상호명 시군구명       경도      위도    p_업소번호     p_경도    p_위도
0      20844443  신전떡볶이  중랑구 127.1014 37.6003  26669769 126.8839 37.4903
1      20844443  신전떡볶이  중랑구 127.1014 37.6003   9171904 127.0330 37.6078
2      20844443  신전떡볶이  중랑구 127.1014 37.6003  23396020 126.9886 37.5742
3      20844443  신전떡볶이  중랑구 127.1014 37.6003  20022143 126.9315 37.5193
4      20844443  신전떡볶이  중랑구 127.1014 37.6003  15484881 127.1477 37.5397
...         ...    ...  ...      ...     ...       ...      ...     ...
93335  20081411  국대떡볶이  서초구 126.9966 37.4814  20072828 126.9138 37.4870
93336  20081411  국대떡볶이  서초구 126.9966 37.4814  20623717 126.8342 37.5402
93337  20081411  국대떡볶이  서초구 126.9966 37.4814  20589842 126.9019 37.4522
93338  20081411  국대떡볶이  서초구 126.9966 37.4814  20595157 127.1310 37.5101
93339  20081411  국대떡볶이  서초구 126.9966 37.4814  17182192 127.1644 37.5569

[93340 rows x 8 columns]

In [8]:
# 두 가게 사이의 거리구하기
# haversine 라이브러리 설치하기 : 두 지점의 위도와 경도를 입력하면 거리를 구해줌
# !pip install haversine

In [9]:
# haversine 사용법
from haversine import haversine
#  서울과 파리의 위도와 경도(위도 경도순)
seoul = [37.541, 126.986]
paris = [48.8567, 2.3508]

# 서울과 파리사이의 거리 계산
# haversine([37.541, 126.986], [48.8567, 2.3508], unit='m')
haversine(seoul, paris, unit='m') # 거리 m

8968562.580161477

In [10]:
# apply로 haversine 함수 이용하여 거리 구하기
df_cross['거리'] = df_cross.apply(lambda x: haversine([x.iloc[4], x.iloc[3]], [x.iloc[7], x.iloc[6]], unit='m'), axis=1)
df_cross

,상가업소번호,상호명,시군구명,경도,위도,p_업소번호,p_경도,p_위도,거리
0,20844443,신전떡볶이,중랑구,127.1014,37.6003,26669769,126.8839,37.4903,22745.8986
1,20844443,신전떡볶이,중랑구,127.1014,37.6003,9171904,127.0330,37.6078,6080.4618
2,20844443,신전떡볶이,중랑구,127.1014,37.6003,23396020,126.9886,37.5742,10356.9671
3,20844443,신전떡볶이,중랑구,127.1014,37.6003,20022143,126.9315,37.5193,17476.6487
4,20844443,신전떡볶이,중랑구,127.1014,37.6003,15484881,127.1477,37.5397,7878.3545
...,...,...,...,...,...,...,...,...,...
93335,20081411,국대떡볶이,서초구,126.9966,37.4814,20072828,126.9138,37.4870,7338.3390
93336,20081411,국대떡볶이,서초구,126.9966,37.4814,20623717,126.8342,37.5402,15751.7354
93337,20081411,국대떡볶이,서초구,126.9966,37.4814,20589842,126.9019,37.4522,8969.1388
93338,20081411,국대떡볶이,서초구,126.9966,37.4814,20595157,127.1310,37.5101,12272.9853
93339,20081411,국대떡볶이,서초구,126.9966,37.4814,17182192,127.1644,37.5569,17013.7789

In [11]:
# 개별 떡볶이 매장과 파리바게뜨와의 거리
df_dis = df_cross.groupby(['상가업소번호', '상호명'])['거리'].min().reset_index()
df_dis

       상가업소번호    상호명       거리
0     8616690  신전떡볶이 392.8313
1     8625310  신전떡볶이 606.1897
2    10520263  죠스떡볶이 327.7421
3    11720327  국대떡볶이  38.6128
4    11751808  신전떡볶이 535.8918
..        ...    ...      ...
255  28488260  죠스떡볶이 788.0267
256  28512949  엽기떡볶이 139.9592
257  28513476  엽기떡볶이 446.9590
258  28514842  엽기떡볶이 753.3187
259  28519528  신전떡볶이 725.6968

[260 rows x 3 columns]

In [12]:
# 프랜차이즈 별 파리바게뜨와의 평균 거리
df_dis.groupby('상호명')['거리'].mean()

상호명
감탄떡볶이   474.1331
국대떡볶이   377.8993
신전떡볶이   420.6615
엽기떡볶이   476.6015
죠스떡볶이   467.2652
Name: 거리, dtype: float64

In [13]:
# 프랜차이즈 별 파리바게뜨와의 평균 거리와 매장개수
df_dis.groupby('상호명')['거리'].agg(['mean', 'count'])

          mean  count
상호명
감탄떡볶이 474.1331     55
국대떡볶이 377.8993     14
신전떡볶이 420.6615     58
엽기떡볶이 476.6015     92
죠스떡볶이 467.2652     41

In [14]:
# 프랜차이즈 별 파리바게뜨와 50m미만인 매장의 평균거리와 매장개수
cond = df_dis['거리'] < 50
df_dis[cond].groupby('상호명')['거리'].agg(['mean', 'count'])

         mean  count
상호명
감탄떡볶이 15.2256      7
국대떡볶이 19.3064      2
신전떡볶이 49.3257      1
엽기떡볶이 27.7970      5
죠스떡볶이 13.6234      5

In [15]:
# 프랜차이즈 별 파리바게뜨와 50m미만인 매장의 평균거리와 매장개수
cond = df_dis['거리'] < 30
df_dis[cond].groupby('상호명')['거리'].agg(['mean', 'count'])

         mean  count
상호명
감탄떡볶이  0.0000      4
국대떡볶이  0.0000      1
엽기떡볶이 17.9833      3
죠스떡볶이  4.7981      4

In [16]:
# 거리에 따라 집계를 해주는 함수
def distance(x):
    cond = df_dis['거리'] < x
    return df_dis[cond].groupby('상호명')['거리'].agg(['mean', 'count'])

distance(100)

         mean  count
상호명
감탄떡볶이 33.6436     10
국대떡볶이 41.0192      3
신전떡볶이 80.7178      5
엽기떡볶이 59.2283     11
죠스떡볶이 51.1618     11

### 감탄떡볶이의 입점전략 시각화하기

In [17]:
pip show pyecharts

Name: pyecharts
Version: 1.9.1
Summary: Python options, make charting easier
Home-page: https://github.com/pyecharts/pyecharts
Author: chenjiandongx
Author-email: chenjiandongx@qq.com
License: MIT
Location: C:\Users\julia\.conda\envs\data_projects\Lib\site-packages
Requires: jinja2, prettytable, simplejson
Required-by: pandasecharts
Note: you may need to restart the kernel to use updated packages.

In [18]:
pip show pandasecharts

Name: pandasecharts
Version: 0.5
Summary: Visualize your pandas data with one-line code
Home-page: https://github.com/gamersover/pandasecharts
Author: gamersover
Author-email: cmathking@gmail.com
License:
Location: C:\Users\julia\.conda\envs\data_projects\Lib\site-packages
Requires: pandas, pyecharts
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [19]:
pip show haversine

Name: haversine
Version: 2.9.0
Summary: Calculate the distance between 2 points on Earth.
Home-page: https://github.com/mapado/haversine
Author: Balthazar Rouberol
Author-email:
License: MIT
Location: C:\Users\julia\.conda\envs\data_projects\Lib\site-packages
Requires:
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [20]:
# 프로젝트 코드
import pandas as pd
from haversine import haversine
from pyecharts.charts import Timeline, Grid
from pandasecharts import echart
import IPython

pd.options.display.max_rows = 6 # 판다스 1.4+ 에서 6행까지만 출력
pd.options.display.float_format = '{:.4f}'.format # 소수점 네자리 까지만 출력
url = 'https://raw.githubusercontent.com/panda-kim/csv_files/main/food_business_seoul_20221231.csv'
tt = ['감탄떡볶이', '국대떡볶이', '죠스떡볶이', '엽기떡볶이', '신전떡볶이']
df = pd.read_csv(url)

# 파리바게뜨 데이터 필터링하고 정제하기
cond1 = df['상호명'].str.contains(r'파리바게뜨|파리바게트')
df_paris = df.loc[cond1, ['상가업소번호', '경도', '위도']].copy()
df_paris = (df_paris
            .set_axis(['p_업소번호', 'p_경도', 'p_위도'], axis=1)
            .reset_index(drop=True))

# 떡볶이 프랜차이즈 데이터 필터링하고 정제하기
df_tt = df.copy()
df_tt['상호명'] = df_tt['상호명'].str.extract(r'({})'.format('|'.join(tt)))[0]
df_tt = (df_tt
         .dropna(subset=['상호명'])
         .iloc[:, [0, 1, 5, 8, 9]]
         .reset_index(drop=True))

# df_tt와 df_paris의 곱집합 만들기
df_cross = df_tt.merge(df_paris, how='cross')

# df_cross에 거리열 만들기
df_cross['거리'] = df_cross.apply(
    lambda x: haversine([x.iloc[4],x.iloc[3]], [x.iloc[7], x.iloc[6]], unit='m'), 
    axis=1)

# 개별 떡볶이 매장과 파리바게뜨와의 거리
df_dis = df_cross.groupby(['상가업소번호', '상호명'])['거리'].min().reset_index()


# 거리에 따라 프랜차이즈별 평균 거리와 매장수를 집계를 해주는 함수
def distance(x):
  cond = df_dis['거리'] < x
  return df_dis[cond].groupby('상호명')['거리'].agg(['mean', 'count'])

In [21]:
# distance 함수로 50m의 집계하기(reset_index로 상호명도 열로 만든다)
df_g = distance(50).reset_index()
df_g

     상호명    mean  count
0  감탄떡볶이 15.2256      7
1  국대떡볶이 19.3064      2
2  신전떡볶이 49.3257      1
3  엽기떡볶이 27.7970      5
4  죠스떡볶이 13.6234      5

In [22]:
# 50m의 데이터로 원형 그래프 만들기
df_g.echart.pie(x='상호명', y='count', figsize=(600, 400),
               radius=['20%', '60%'], label_opts={'position':'outer'},
               title='감탄떡볶이의 입점전략은 과연 파리바게뜨 옆인가?',
               legend_opts={'pos_right':'0%', 'orient':'vertical'},
               subtitle='50m 이내 매장수').render()
IPython.display.HTML(filename='250829_pie_chart.html')

In [23]:
# 앞서 만든 그래프를 timeline으로 만들기
tl = Timeline({'width':'600px', 'height':'400px'})
for i in [10000, 100, 50, 30]:
    df_g = distance(i).reset_index()
    pie1 = df_g.echart.pie(x='상호명',
                           y='count',
                           figsize=(600, 400),
                           radius=['20%', '60%'],
                           label_opts={'position':'outer'},
                           title='감탄떡볶이의 입점전략은 과연 파리바게뜨 옆인가?',
                           legend_opts={'pos_right':'0%', 'orient':'vertical'},
                           subtitle=f'{i}m 이내 매장수')
    tl.add(pie1, f'{i}m').render()
IPython.display.HTML(filename='250829_pie_timeline_chart.html')